language: c
os: linux
dist: xenial
cache:
  directories:
    - ~/arduino_ide
    - ~/.arduino15/packages/
git:
  depth: false
  quiet: true
env:
  global:
    - PRETTYNAME="BQ24298 Battery Charger"
    # You can uncomment this to explicitly choose an (old) version of the Arduino IDE
    #- ARDUINO_IDE_VERSION="1.8.10"
before_install:
  - source <(curl -SLs https://raw.githubusercontent.com/akkoyun/BQ24298/main/install.sh)
install:
  # Note that every library should be installed in a seperate command
   - arduino --install-library "I2C_Functions"
script:
  - build_main_platforms
notifications:
  email:
    on_success: change
    on_failure: change
